# - - - - - - - - - - - - - - - - #
#    Component SCSS lint config   #
# - - - - - - - - - - - - - - - - #

# Linter Options
options:
  merge-default-rules: false

# Default files
files:
  include: './src/**/*.scss'

# Rule Configuration
rules:

  # Extends
  extends-before-mixins: 2
  extends-before-declarations: 2
  placeholder-in-extend: 0

  # Mixins
  mixins-before-declarations: 0

  # Line Spacing
  one-declaration-per-line: 2
  empty-line-between-blocks: 2
  single-line-per-selector: 2

  # Disallows
  no-color-keywords: 2
  no-color-literals: 0
  no-css-comments: 0
  no-debug: 2
  no-duplicate-properties: 2
  no-empty-rulesets: 2
  no-extends: 0
  no-ids: 2
  no-important: 1
  no-invalid-hex: 2
  no-mergeable-selectors: 1
  no-misspelled-properties: 2
  no-qualifying-elements: 2
  no-trailing-zero: 0
  no-transition-all: 2
  no-url-protocols: 1
  no-vendor-prefixes: 1
  no-warn: 1

  # Nesting
  force-attribute-nesting: 1
  force-element-nesting: 1
  force-pseudo-nesting: 1

  # Name Formats
  function-name-format: 1
  mixin-name-format: 1
  placeholder-name-format: 1
  variable-name-format: 0

  # Style Guide
  border-zero: 0
  brace-style: 2
  clean-import-paths: 1
  empty-args: 1
  hex-length: 1
  hex-notation: 1
  indentation:
    - 2
    -
      size: 2
  leading-zero: 0
  nesting-depth: 2
  property-sort-order: 0
  quotes: 1
  shorthand-values: 1
  url-quotes: 2
  variable-for-property: 0
  zero-unit: 1

  # Inner Spacing
  space-after-comma: 2
  space-before-colon: 1
  space-after-colon: 2
  space-before-brace: 2
  space-before-bang: 1
  space-after-bang: 1
  space-between-parens: 1

  # Final Items
  trailing-semicolon: 1
  final-newline: 1
